#!/usr/bin/env node

const { promises: fs, constants: fsConstants } = require("fs");
const path = require("path");
const dateFns = require("date-fns");

function abort(message) {
  console.error(message);
  process.exit(1);
}

function configPath(filePath) {
  const configDirectory = "/Users/bknight/Desktop/scratchpad/times-txt";
  return path.resolve(configDirectory, filePath);
}

async function copyTemplate() {
  const src = configPath("_template.md");
  const dest = configPath(dateToDocumentName(Date.now()));

  try {
    await fs.copyFile(src, dest, fsConstants.COPYFILE_EXCL);
  } catch (error) {
    abort(error.message);
  }
}

function dateToDocumentName(date) {
  const today = dateFns.format(date, "yyyy-MM-dd");
  return `${today}.md`;
}

function getHours(doc) {
  const entryCount = doc
    .match(/ (?<entries>[-x]{4}) /gi)
    .join("")
    .replace(/[ -]/g, "").length;

  return entryCount / 4;
}

function getBreakdown(doc) {
  const timeEntries = doc
    .split("\n")
    .slice(2)
    .filter((line) => line[0] === "|")
    .slice(0, -1)
    .map((line) => line.split("|").filter(Boolean))
    .map(([title, ...times]) => [
      title.replace(/\\*/g, "").trim(),
      getHours(times.join()),
    ])
    // Move "spread" time to bottom
    .sort((a, b) => (a[0] === "spread" ? 1 : b[0] === "spread" ? -1 : 0));

  const longestTitle = timeEntries.reduce(
    (longest, [title]) => Math.max(longest, title.length),
    0
  );

  const formatTitle = (str) => str.padEnd(longestTitle + 2, ".");
  const formatTime = (num) => num.toFixed(2);
  const formatEntry = ([title, time]) =>
    `- ${formatTitle(title)}${formatTime(time)}\n`;

  return timeEntries.reduce(
    (output, timeEntry) => output.concat(formatEntry(timeEntry)),
    "\n"
  );
}

function parseArguments() {
  const defaultArguments = {
    filename: dateToDocumentName(Date.now()),
    shouldCopyTemplate: false,
    showHelp: false,
    showVersion: false,
  };

  return process.argv.slice(2).reduce((args, command) => {
    if (command === "--help" || command == "-h") {
      args.showHelp = true;
    } else if (command === "--version" || command == "-V") {
      args.showVersion = true;
    } else if (command === "new") {
      args.shouldCopyTemplate = true;
    } else if (command === "today") {
      args.filename = dateToDocumentName(Date.now());
    } else if (isFinite(Number(command))) {
      args.filename = dateToDocumentName(
        dateFns.addDays(Date.now(), Number(command))
      );
    } else if (/\.md$/.test(command)) {
      args.filename = command;
    } else if (isFinite(dateFns.parseISO(command).getTime())) {
      args.filename = `${command}.md`;
    } else if (new RegExp(command).test("yesterday")) {
      args.filename = dateToDocumentName(dateFns.subDays(Date.now(), 1));
    } else {
      abort(`unknown argument: ${command}`);
    }

    return args;
  }, defaultArguments);
}

async function getTimeSummary(filename) {
  const filePath = configPath(filename);
  const contents = await fs.readFile(filePath, { encoding: "utf8" });
  const hours = getHours(contents);
  const output = [];

  output.push(`Current:     ${hours} hr`);

  if (hours < 8) {
    const remainingHours = 8 - hours;
    const endTimestamp = dateFns.addMinutes(
      Date.now(),
      remainingHours * 60 // HACK: dateFns.addHours seems to only apply whole hours, not minutes
    );
    const endTime = new Date(endTimestamp).toLocaleTimeString();

    output.push(`Remaining:   ${remainingHours} hr - ${endTime}`);
  }

  output.push(getBreakdown(contents));

  return output.join("\n");
}

function showHelp() {
  console.log(
    `
Prints timesheet hours

Usage:
  get-time [options] [command]

Options:
  -h, --help     output usage information and exit
  -V, --version  output the version number and exit

Commands:
  new       creates a new timesheet for the current day; no options
  today     shows time for today
  [number]  shows time for the day {n} days from now (positive or negative)`.trim()
  );
}

async function main() {
  const args = parseArguments();

  if (args.showHelp) {
    showHelp();
    return;
  }

  if (args.showVersion) {
    const { name, version } = require("./package.json");
    console.log(`${name}@${version}`);
    return;
  }

  if (args.shouldCopyTemplate) {
    return await copyTemplate();
  }

  if (args.filename !== null) {
    console.log(await getTimeSummary(args.filename));
  }
}

main();
